### ISSUE TITLE
extra-large screens or Firefox: 'here' link shows wrong colours

### ISSUE THREAD

**Issue by BarboraDoslikova** [BarboraDoslikova/games-website#6]
On extra-large screens or in Firefox (don't know which one?), the 'here' link shows as light blue, hover and active shows the right colour, but visited shows dark blue
But caniuse.com doesn't say that :link and :visited aren't supported in Chrome or Firefox...
So where is the problem?
@radestepan

**Comment by BarboraDoslikova** [comment]
I included the :link (note there before) and put the :visited after :hover and :active -> works now.

**Comment by radekstepan** [comment]
Usually choosing a color for the `a` element works, otherwise the browser goes for its default. You can see these default rules when you (again) use Developer Tools in your browser. It shows you where the rule is coming from.

**Comment by BarboraDoslikova** [comment]
Makes sense, thanks!
